#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: baidu_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url, baidu.*
#        - id: query_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url, qq.
#        - id: renren-fast
#          uri: lb://renren-fast # 负载均衡到renren-fast服务
#          predicates:
#            - Path=/api/** # 后端接口/api前缀，路由到lb://renren-fast
#          filters: # 路径重写
#            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
