#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: baidu_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu.*
#        - id: query_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq
#        - id: ware_route
#          uri: lb://gulimall-ware
#          predicates:
#            - Path=/api/wms/**
#          filters:
#            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
#        - id: member_route
#          uri: lb://gulimall-member
#          predicates:
#            - Path=/api/ums/**
#          filters:
#            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
#        - id: third_part_route
#          uri: lb://gulimall-third-party
#          predicates:
#            - Path=/api/thirdparty/**
#          filters:
#            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}
#        - id: gulimall-product
#          uri: lb://gulimall-product
#          predicates:
#            - Path=/api/pms/**,/hello
#          filters:
#            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
#        - id: renren-fast
#          uri: lb://renren-fast # 负载均衡到renren-fast服务
#          predicates:
#            - Path=/api/** # 后端接口/api前缀，路由到lb://renren-fast
#          filters: # 路径重写
#            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
#        - id: gulimall-host-product
#          uri: lb://gulimall-product # 负载均衡到gulimall-product服务
#          predicates:
#            - Host=gulimall.com,item.gulimall.com
#        - id: gulimall-host-search
#          uri: lb://gulimall-search # 负载均衡到gulimall-product服务
#          predicates:
#            - Host=search.gulimall.com
#        - id: gulimall-host-auth
#          uri: lb://gulimall-auth-server # 负载均衡到gulimall-auth-server认证中心
#          predicates:
#            - Host=auth.gulimall.com
#        - id: gulimall-cart
#          uri: lb://gulimall-cart # 负载均衡到gulimall-cart购物车
#          predicates:
#            - Host=cart.gulimall.com
#        - id: gulimall-order
#          uri: lb://gulimall-order # 负载均衡到gulimall-cart购物车
#          predicates:
#            - Host=order.gulimall.com